#
# Format:
#
# <stage name>:
#   app: <Heroku app name>
#   stack: <Heroku stack, optional>
#   tag: <git tag pattern, optional>
#   repo: <git repository, optional>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#

production:
  app: ccmarket
  stack: cedar
  tag: production/*
  config:
    BUNDLE_WITHOUT: "development:test"

staging:
  stack: cedar
  app: ccmarket-staging
  config: &default
    BUNDLE_WITHOUT: "development:test"
  addons:
    - flying_sphinx:ceramic
    - memcachier:dev
    - newrelic:wayne
    - papertrail:choklad
    - scheduler:standard

demo:
  app: ccmarket-demo
  config: *default
